export const GET_TOKEN = "GET_TOKEN";
export const SET_TOKEN = "SET_TOKEN";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS"
export const GET_PRODUCT_BY_SLUG = "GET_PRODUCT_BY_SLUG"
