export { default as Home } from "./Home/Home";
export { default as About } from "./About/About";
export { default as Product } from "./Product/Product";
export { default as Contact } from "./Contact/Contact";
export { default as Shopcart } from "./Shopcart/Shopcart";
export { default as SignIn } from "./SignIn/SignIn";
export { default as SignUp } from "./SignUp/SignUp";
export { default as DetailProduct } from "./DetailProduct/DetailProduct";
export { default as NotFound } from "./NotFound/NotFound";
